defaults: &defaults
  
  database: 
    namespace: 'nyhetis:db'
    host: localhost
    port: 1111
    user: carlos
    password: 1234

  server:
      host: localhost
      port: 9393
  
  websources: 
      - 'http://www.ideal.es/jaen'
      #- 'http://www.diariojaen.es'
      - 'http://andaluciainformacion.es/jaen'

development: 
  <<: *defaults

test:
  <<: *defaults
  database: 
    namespace: 'nyhetis:db:test'
    host: localhost
  websources:
    - 'http://localhost:7541'
  newspaper_mock:
    host: localhost
    port: 7541

integration:
  <<: *defaults
  newspaper_mock:
    host: localhost
    port: 7541

  websources: 
    - 'http://localhost:7541'

production: 
  <<: *defaults